name: Despliegue Laserdreans

on:
  push:
    branches:
      - main  # O la rama que estÃ©s usando

jobs:
  web-deploy:
    name: ðŸŽ‰ Desplegar sitio
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Obtener cÃ³digo
      uses: actions/checkout@v3

    - name: ðŸš€ Desplegar vÃ­a FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 109.106.251.247
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: public_html/
        timeout: 9999
        # Los secretos deben configurarse en GitHub:
        # FTP_USERNAME: u499089589.lsd
        # FTP_PASSWORD: Blanca1938@